spring:
  application:
    name: payment-service
  
  # Base de données H2 en mémoire
  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  # Configuration Kafka CONSUMER
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.example.paymentservice.dto,com.example.orderservice.dto"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Port du service
server:
  port: 8082

# Topics Kafka
kafka:
  topic:
    orders: orders-topic
    payments: payments-topic

# Logs pour debug
logging:
  level:
    com.example.paymentservice: DEBUG
    org.springframework.kafka: INFO